### ISSUE TITLE
nested describes (suites) is unsupported

### ISSUE THREAD

**Issue by ibolmo** [ibolmo/jasmine-jstd-adapter#1]

**Comment by mhevery** [comment]
I ran into the same issue.

**Comment by ibolmo** [comment]
Yep. It's a matter of implementation. I had sent a proposal to the JSTD group, but they'd rather change the Runner rather than open up the interface I had asked for. 

At the moment, I'm busy with another project. If you're welcomed to the prospect of getting dirty, we can work collab. on supporting nested describes.

**Comment by sullimander** [comment]
This seems to be working for me. Not sure when it was fixed, but its working now

**Comment by ibolmo** [comment]
Yep. mhevery fixed it a while back. Thanks for your pull request. I'll take a look some time tonight.
