### ISSUE TITLE
specs duplicated when modifying any loaded JS file

### ISSUE THREAD

**Issue by mattfysh** [ibolmo/jasmine-jstd-adapter#13]
I'm running jsTestDriver with Jasmine and this adapter. Every time I update any of the JS files in the config file, specs appear to be duplicated and appended to the existing test suite.

e.g. this first run:

```
......
Total 6 tests (Passed: 6; Fails: 0; Errors: 0) (3.00 ms)
  Firefox 4.0 Windows: Run 6 tests (Passed: 6; Fails: 0; Errors 0) (3.00 ms)
```

can easily turn into this, by simply adding spaces and saving any JS file...

```
..............................................
Total 46 tests (Passed: 46; Fails: 0; Errors: 0) (3.00 ms)
  Firefox 4.0 Windows: Run 46 tests (Passed: 46; Fails: 0; Errors 0) (3.00 ms)
```

**Comment by mattfysh** [comment]
Needed to add the `--reset` command line flag to jsTestDriver. as I'm on windows, I've setup the scripts via external tools in eclipse and hadn't seen the server.sh and test.sh files. good work on the lib :)

**Comment by ibolmo** [comment]
Cool. Thanks for informing me of this behavior. Glad everything worked out.
