### ISSUE TITLE
adapter doesn't support running single test case via --tests flag

### ISSUE THREAD

**Issue by vitalii-dmytruk** [ibolmo/jasmine-jstd-adapter#22]
The adapter is able to run all tests included in the JSTestDriver configuration file (--tests all).
But it isn't possible to run single test or test case (--tests TestCaseName). JasmineAdapter runs all tests instead.

**Comment by segrey** [comment]
+1 please fix

**Comment by BanksySan** [comment]
+1 from me too please, this would be really, really useful.

**Comment by annakryzhko1** [comment]
+1, I'm looking forward for this feature

**Comment by ibolmo** [comment]
I'm no longer maintaining JSTD adapter since I'm no longer using JSTD. You may want to look at [Karma](http://karma-runner.github.io/0.10/index.html).
