### ISSUE TITLE
Doesn't it support jasmine 2.0.0 version?

### ISSUE THREAD

**Issue by qcgm1978** [ibolmo/jasmine-jstd-adapter#26]
Hello:
 I updated the jasmine lib to 2.0.0 version and have found adapter doesn't support it. Will it support the newest version?

Best Regards,
Youth

**Comment by ibolmo** [comment]
As mentioned in the description of the project, this repo is no longer supported. Take a look at http://karma-runner.github.io/0.10/index.html

**Comment by qcgm1978** [comment]
Thank you, I've known what Karmer is after you recommended and integrated it into webstorm.
