### ISSUE TITLE
Supporting Jasmine latest versions

### ISSUE THREAD

**Issue by 0ct0d4n** [ibolmo/jasmine-jstd-adapter#29]
Hi!, I would like to continue in a fork the support for jasmine.

What should I Know to continue the support?

**Comment by ibolmo** [comment]
If you give me the weekend I can add jasmine latest support. I didn't
think, though, that folks still used jstd.

**Comment by 0ct0d4n** [comment]
Thanks Man!

**Comment by ibolmo** [comment]
After review, I'm beginning to believe that it's a bigger headache than solution. Have you considered [karma](https://karma-runner.github.io/1.0/index.html)? It's effectively JSTD.

**Comment by 0ct0d4n** [comment]
In fact, I am trying Karma right now and you're right, Karma is better. Thanks!
