### ISSUE TITLE
Wrong this in it()

### ISSUE THREAD

**Issue by mhevery** [ibolmo/jasmine-jstd-adapter#5]
<pre><code>
describe('bug', function(){
  it('should spy on function', function(){
    var fn = jasmine.createSpy();
    this.spyOn(fn).andReturn(123); // <- this fails as this.spyOn is undefined
  });
});
</code></pre>

**Comment by ibolmo** [comment]
Try without the `this.`. I suspect `this` is bound to something else. I'd have to investigate if there's a way to bind it to `jasmine`.
