### ISSUE TITLE
frame.before is undefined error

### ISSUE THREAD

**Issue by mkleene** [ibolmo/jasmine-jstd-adapter#6]
It appears that the variable 'frame' in the function 'frame(parent, name)' was inlined.  The problem with that is that the variable 'frame' is used inside a function in its definition, leading to this error.  Introducing the variable 'frame' and returning it fixes the issue.

**Comment by ibolmo** [comment]
Thanks mkleene. Can you check out http://github.com/cpojer/jasmine-jstd-adapter. He has improved and fixed a couple of bugs since my absence to the project.

**Comment by mkleene** [comment]
Thanks, I'll have a look.
