### ISSUE TITLE
Asynchronous spec does not work

### ISSUE THREAD

**Issue by vojtajina** [ibolmo/jasmine-jstd-adapter#8]
Methods waits(), waitsFor() does not work with jstd adapter...
http://pivotal.github.com/jasmine/async.html

**Comment by chillu** [comment]
FYI, I've followed up on this in the jasmine mailinglist: https://groups.google.com/forum/#!topic/jasmine-js/3j2DLb9vKbE

**Comment by ibolmo** [comment]
Fixed previously, but added coverage: https://github.com/ibolmo/jasmine-jstd-adapter/commit/cdc7f40272016eea72386bc4e03b7dc81debc2dc
