### ISSUE TITLE
Spies should be removed after each spec

### ISSUE THREAD

**Issue by vojtajina** [ibolmo/jasmine-jstd-adapter#9]
After any spec, test spies should be removed.
This does not work with JSTD adapter.

I will analyze this problem and solve.

**Comment by ibolmo** [comment]
Were you able to solve this?

**Comment by vojtajina** [comment]
I'm sorry, I was very bussy at work, so I wasn't working on that.

But I have updated adapter to latest version and the issue has already been fixed !
So, I'm closing this issue.
